apiVersion: v1
kind: Service
metadata:
  name: mlip-walmart-forecast-service
spec:
  selector:
    app: mlip-walmart-forecast-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30050